### ISSUE TITLE
New skin for Yeast, UH1H

### ISSUE THREAD

**Issue by utley1005** [rcflyinghokie/JTF-13-Skinpack#48]
can I get this skin incorporated in the next update? 

![Screen_210206_131041](https://user-images.githubusercontent.com/74980467/107761099-d075c380-6cf8-11eb-97ca-a6b196be3f1e.png)

**Comment by rcflyinghokie** [comment]
Just make a pull request in git.

**Comment by Vishari** [comment]
has been added since previous git push
